/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'venka' at '8/10/16 12:38 AM' with Gradle 2.14
 *
 * @author venka, @date 8/10/16 12:38 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
